name: nssapp
description: NSS BPHC app
publish_to: "none"
version: 0.0.1+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  grouped_list: ^4.0.0
  flutter_svg:
  intl:
  http: ^0.13.3
  provider: ^6.0.0
  shared_preferences: ^2.0.6
  flutter_secure_storage: ^4.2.1
  jwt_decoder: ^2.0.1
  # flutter_cache_manager: ^3.1.2
  url_launcher: ^6.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
